### ISSUE TITLE
Rename dotnetapp-prod to dotnetapp

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker-samples#105]
We had a scheme in the past for our naming, but based on changes in the ecosystem and our own learning, I'm starting to wish we didn't have "-prod" in the sample names and just considered the default sample to be the right one and everything else to be variations. Basically, "prod" should be our default use case.

Thoughts on renaming?

**Comment by MichaelSimons** [comment]
This was resolved with https://github.com/dotnet/dotnet-docker/pull/362.
