### ISSUE TITLE
Confusing separation of dev/prod

### ISSUE THREAD

**Issue by jstaro** [dotnet/dotnet-docker-samples#108]
Looking at these samples, I am at a loss as to how to structure my project for both dev and prod work (the usual dev feedback loop with support for building a deployable production image). Why are these samples completely separate?

If I understand Docker properly (granted, I might not), we should have two `Dockerfile`s, one for prod and one for dev. The dev sample has the `Dockerfile` inside the _solution_ folder, whereas the prod sample has the *Dockerfile* inside the `dotnetapp` _project_ folder.

I am especially confused when `docker-compose` enters the picture here. To be precise: trying to reconcile the structure generated by VS's "Add Docker support" (which I'm guessing might get superseded at some point) and these samples.

**Comment by richlander** [comment]
Sorry to confuse you! We are in the process of updating the samples. We started with very simple samples  (single project/directory) and have more recently moved to more complex samples (multiple project/directory). The more complex samples are more useful, IMO. They are more representative of regular projects.

The initial samples were based on the output of `dotnet new console`. These were a good start to our samples, but a bit too simple on our part. Hope that helps.

**Comment by viperx77** [comment]
I had the exact same question as @jstaro.  Why a distinction between prod and dev.  Isn't that the point of Docker to remove the "works on my machine" problem.  If we are building different images for dev vs prod it seems it negates that principle.

On another note, it's refreshing to see that your response was within 4 hours of me researching the exact same topic.  I look forward to new samples.

**Comment by richlander** [comment]
I'm working on the new samples .... PR @ https://github.com/dotnet/dotnet-docker/pull/362

**Comment by MichaelSimons** [comment]
This issue was resolved with https://github.com/dotnet/dotnet-docker/pull/362.  See the new samples at https://github.com/dotnet/dotnet-docker/blob/master/samples/README.md
