### ISSUE TITLE
Readme does not say what this sample is/does

### ISSUE THREAD

**Issue by timomta** [dotnet/dotnet-docker-samples#21]
Hello, it would be nice to see some explanation of what the sample is and does so I know if it addresses what I'm looking for before investing time in downloading and going through the code.

**Comment by MichaelSimons** [comment]
@kendrahavens - Can you take a look?

**Comment by kendrahavens** [comment]
Noted, I'll add more explanation to the READMEs.

**Comment by MichaelSimons** [comment]
Closing per @kendrahavens fix.
