### ISSUE TITLE
compatibility issue?

### ISSUE THREAD

**Issue by ekitagawa** [dotnet/dotnet-docker-samples#42]
Firstly, thank you for making a simple self-contained sample.  It really helps!
 
I tried to run it, and got following error.
> PS C:\Program Files> docker run microsoft/dotnet-samples:dotnetapp-nanoserver
> The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
>   - Check application dependencies and target a framework version installed at:
>       C:\Program Files\dotnet\shared\Microsoft.NETCore.App
>   - The following versions are installed:
>       1.0.3
>   - Alternatively, install the framework version '1.0.4'.

Maybe, we should update this to use "1.0.4-runtime"?
>FROM microsoft/dotnet:1.0-runtime-nanoserver
 
My server is on "17.03.0-ee-1".
 
Thank you in advance.

**Comment by MichaelSimons** [comment]
@ekitagawa, Can you try re-pulling the image (e.g. `docker pull microsoft/dotnet-samples:dotnetapp-nanoserver`) and try running a newer version?  We discovered the issue you encountered earlier today and rebuilt the images.

**Comment by ekitagawa** [comment]
ah... sorry... I pulled the image, and it worked as expected.  "docker inspect" is showing newer build number indeed.  thank you for such a quick response!

**Comment by MichaelSimons** [comment]
@ekitagawa - Glad to help out.  I apologize for mistake on our side which caused the bad image to be pushed.
