### ISSUE TITLE
Update samples

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker-samples#52]
I think we should update our samples in this way:

- [x] Make sure all samples are 1.1.
- [x] Delete the "current" sample. I no longer makes sense.
- [x] Create a new branch for 2.0 samples.
- [x] Merge the 2.0 branch into master when we ship 2.0 RTM and no longer have 1.x samples.

/cc @kendrahavens

**Comment by MichaelSimons** [comment]
Seems like this is being fixed with #63.

**Comment by richlander** [comment]
I totally forgot about this. Yes.
