### ISSUE TITLE
Commands in all the three dotnetapp examples use the same name

### ISSUE THREAD

**Issue by StefH** [dotnet/dotnet-docker-samples#65]
There are three examples called **dotnetapp**

- dotnetapp-dev
- dotnetapp-prod
- dotnetapp-selfcontained

However in the three examples, the `docker build -t %%%` and `docker run --rm %%%`, the same name **dotnetapp** is used.

Maybe a good idea to rename the %%% also with the fullname, like dotnetapp-dev, dotnetapp-prod and dotnetapp-selfcontained.

**Comment by MichaelSimons** [comment]
@richlander - I like this suggestion.  What do you think about updating the [PR ](https://github.com/dotnet/dotnet-docker-samples/pull/63) you are working on to include this?

**Comment by richlander** [comment]
Fair. I'll change that.
