### ISSUE TITLE
Include sample for DotNet.Watcher.Tools for development time.

### ISSUE THREAD

**Issue by alexsandro-xpt** [dotnet/dotnet-docker-samples#68]
In development should be have a way to run my project with `dotnet watch run` to gain development time when I test my app.

**Comment by kendrahavens** [comment]
Hey @alexsandro-xpt. Thank you for opening this. We are currently trying to figure out the documentation gaps that would make this approachable. We've had prototypes of this working, but it takes a lot of configuration right now and its not in a state or pattern that we want to recommend to customers yet.

**Comment by alexsandro-xpt** [comment]
Alright @kendrahavens, I haved tested it in this repository https://github.com/alexsandro-xpt/WatchRunDocker in both v1.1 and v2.0 dotnet core version at master and dotnetcore2 branch, may be this could help something.

**Comment by MichaelSimons** [comment]
Issue moved to [dotnet/dotnet-docker #394](https://github.com/dotnet/dotnet-docker/issues/394) via [**ZenHub**](https://www.zenhub.com/)
