### ISSUE TITLE
Add example with Project References

### ISSUE THREAD

**Issue by IvanJosipovic** [dotnet/dotnet-docker-samples#84]
The samples will not build if there are external project references.
Can you please add an example that uses external project references?

**Comment by MichaelSimons** [comment]
@IvanJosipovic - Can you clarify what you mean by external project?  Is it another project within the same solution?  Is it a project outside the solution?  Could you share a csproj that illustrates this?

**Comment by IvanJosipovic** [comment]
I've used the dotnet-docker-samples/aspnetapp template. If I add a project reference, it will no longer build.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Project.Core\Project.Core.csproj" />
  </ItemGroup>

</Project>

**Comment by EduardoPires** [comment]
If I have this structure:

-src
-- WebApp
-- Data
-- Business

I can't get all *.csproj to build, and the build fails because the csproj of the WebApp depends of others.

Any idea?

**Comment by ravimeda** [comment]
Thanks @EduardoPires and @IvanJosipovic for trying out the samples. If you haven't already, please could see if [Visual Studio Tools for Docker](https://docs.microsoft.com/en-us/aspnet/core/publishing/visual-studio-tools-for-docker) would fit your need?

**Comment by PeterSteen01** [comment]
Hi i also have this issue as i'm sure most serious usage of docker w core 2.0 projects would have. It would be great if you could show us docker noob's how to include and build our project references. 

in advance thanks

Peter Steen Nielsen

**Comment by OnamChilwan** [comment]
Any ideas how to do this, I am struggling too. I am also like @PeterSteen01 a docker noob.

**Comment by ravimeda** [comment]
Here is a sample that demonstrates the usage of project reference (https://github.com/ravimeda/dotnet-docker-samples/tree/ref-sample/ref-sample). 

This sample contains a _dotnet_ solution with two projects - a console project and a class library.  The console project references the class library. A Dockerfile is provided to demonstrate how to build this project.

Steps to run this sample are -

```console
git clone https://github.com/ravimeda/dotnet-docker-samples.git
cd dotnet-docker-samples
git checkout ref-sample
cd ref-sample
docker build -t ref-sample .
docker run --rm ref-sample Hello .NET Core from Docker
```

Please give it a try.

Edit: (11/6) Added description of the sample. (11/2) Included git clone command.

**Comment by wadinj** [comment]
Works perfectly, exactly what I was looking for.
Thanks @ravimeda

**Comment by ravimeda** [comment]
Glad to know!

**Comment by OnamChilwan** [comment]
The example suggests putting the docker file at the same level as the solution. Shouldn't it live at the same level as the csproj or is this the only to get it working?

**Comment by MichaelSimons** [comment]
@OnamChilwan - If your Dockerfile needs to COPY/ADD in assets outside of the project folder (e.g other projects), then it has to be placed within a parent folder that contains all of the required assets.  This is required in order to get those assets into the [Docker build context](https://docs.docker.com/engine/reference/builder/#usage).

**Comment by OnamChilwan** [comment]
@MichaelSimons, if I had multiple deployable items in the same solution this would mean having multiple docker files at solution level? Apologies for asking what might seem an obvious answer. My understanding is that you can have only one docker file..

**Comment by MichaelSimons** [comment]
@OnamChilwan - You can have multiple Dockerfiles in a folder.  You can name them whatever is appropriate to distinguish them and build them with the [-f option](https://docs.docker.com/engine/reference/commandline/build/#specify-a-dockerfile--f). The [self-contained sample](https://github.com/dotnet/dotnet-docker-samples/tree/master/dotnetapp-selfcontained) illustrates this.
