### ISSUE TITLE
Build fails since Docker daemon is not running.

### ISSUE THREAD

**Issue by ravimeda** [dotnet/dotnet-docker-samples#87]
First build task to invoke a Docker command (`docker system prune`) failed likely because the daemon is not running. For example, (https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/index?buildId=1052676&_a=summary)

```
2017-10-11T03:01:05.4286013Z ##[command]docker system prune -a -f
2017-10-11T03:01:05.5001821Z error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/containers/prune: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
2017-10-11T03:01:05.5470492Z ##[error]Process completed with exit code 1.
```

Possible solutions -

1. Ensure the `Start Docker when you log in` option is enabled.
2. Restart Docker service as the first step in the build. `Start-Service -Name com.docker.service` and  `Start-Service -Name docker`

**Comment by ravimeda** [comment]
Rate of occurrence of this issue is less than 1 in 10. Not sure of the priority of addressing this issue.

I'm thinking of add a startup script similar to the one shown below on Windows build agents. Please let me know if you have any suggestions.

```PowerShell
function StartServices
{
    param (
        [string[]]$ServiceNames
    )

    $ServiceNames | % {
        $retryCount = 0
        $retries = 5
        while ($retryCount -lt $retries)
        {
            Start-Service -Name $_ -ErrorAction Continue -ErrorVariable startSvc
            if ($startSvc.Count -eq 0)
            {
                break
            }
            $retryCount += 1
            Write-Warning "Retry $retryCount of $retries..."
            sleep -Seconds (Get-Random -Minimum 3 -Maximum 10)
        }
        Get-Service -Name $_
    }
}

$servicesToStart = "docker", "com.docker.service"
StartService -ServiceNames $servicesToStart
```

**Comment by MichaelSimons** [comment]
I think fixing this should be a priority.  These failure are consistent and always happen at the most inconvenient times.  I would suggest pinging Ilya on your proposed fix.

**Comment by ravimeda** [comment]
Requested DDIT to set Recovery options on Docker services for each VM in DotNet-Infra pool. Refer http://ddweb/techease/TicketEdit.aspx?id=1536152

![image](https://user-images.githubusercontent.com/12752450/31699841-d9641652-b38a-11e7-9ba0-eede77b1a54e.png)

**Comment by ravimeda** [comment]
Though the service Recovery options are set correctly, it is required to ensure `C:\Program Files\Docker\Docker\Docker for Windows.exe` is included in the startup programs.

**Comment by ravimeda** [comment]
We can consider starting `Docker for Windows.exe` in a build task through the script shown below -

```PowerShell
$retryCount = 0
$retries = 5

while ($retryCount -lt $retries)
{
    Get-Process -Name "Docker for Windows" -ErrorVariable dockerProc
    if ($dockerProc -ne 0)
    {
        $dockerExe = Join-Path ${$env:ProgramFiles} "Docker\Docker\Docker for Windows.exe"
        if (-not (Test-Path $dockerExe -PathType Leaf))
        {
            $dockerExe = Join-Path ${env:ProgramFiles(x86)} "Docker\Docker\Docker for Windows.exe"
        }
        & "$dockerExe"
        sleep -Seconds (Get-Random -Minimum 30 -Maximum 60)
        $retryCount += 1
    }
    else
    {
        break
    }
}
```

**Comment by MichaelSimons** [comment]
This issue has been resolved by DDIT.

**Comment by ravimeda** [comment]
Thanks Michael for working with Ilya in resolving this issue.
